### ISSUE TITLE
Writing back to the model

### ISSUE THREAD

**Issue by kleineroscar** [cinaq/mendix-cli#2]
Hey @xiwenc ,
this tool looks great and is definitely something the community desparately needed. I played around a little bit and tried if we can also programmtically modify the mpr file (like the MPRTool does).
Is that something you already explored? I haven't tried writing back to the model yet, but I am unable to generate the same hashes for the content even without modifying.

My main use case would be to do mass-edits as it is pretty cumbersome to manually add 50+ attributes to an entity.

BR
Oscar

**Comment by xiwenc** [comment]
No, i have not explored the option to update the MPR file. The hashing is indeed the issue. Since it is proprietary to Mendix, it will probably not be trivial to determine what it is. Unless someone shares the algorithm.

I might give it a shot when i have time.

**Comment by xiwenc** [comment]
Today I attended a session about the upcoming feature of extending the Mendix Studio Pro. It's probably a better bet to implement refactor tools as extensions instead. These extensions will have read-write access to the model it seems. Fingers crossed. I'm closing this issue as I do not expect to figure out the hashing method.  Feel free to re-open this If desired.
